### ISSUE TITLE
UdpPinger vs UpdPinger

### ISSUE THREAD

**Issue by tbaschak** [facebook/UdpPinger#2]
In the file `README.md` there is several mentions each of `UdpPinger` and `UpdPinger`. I am not sure which is correct/intended but the repo is named `UdpPinger` which suggests thats the intended spelling. 

I think there shouldn't be confusion about the project's name in the README.

**Comment by aijayadams** [comment]
Thanks for pointing this out @tbaschak. I've updated the README to the intended name `UdpPinger`.
