### ISSUE TITLE
Fails to build with Folly v0.57.0

### ISSUE THREAD

**Issue by kvikas** [facebook/UdpPinger#4]
Documentation says it builds with Facebook Folly v0.57.0, but it fails to compile with Folly v0.57.0. Specifically this is the problem:
1. [UdpPinger.cpp](https://github.com/facebook/UdpPinger/blob/master/uping/UdpPinger.cpp#L390) uses `folly::NotificationQueue::make`
2. `folly::NotificationQueue::make` is not part of [v0.57.0](https://github.com/facebook/folly/blob/v0.57.0/folly/io/async/NotificationQueue.h). It was added later.

Can we fix the documentation?

**Comment by aijayadams** [comment]
Thanks for letting me know, I've removed the release number and just pointed to Folly in keeping with the style we use in wangle.
